{{- range .Values.services  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-configmap
  namespace: {{ $.Values.namespace }}
  labels:
    helm.sh/chart: telemetry-1.0.0
    app.kubernetes.io/name: telemetry
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/version: {{ $.Values.image.tag }}
    app.kubernetes.io/managed-by: Helm
data:
  DISABLE_PROMETHEUS: "{{ $.Values.envs.disablePrometheus }}"
  TELEMETRY_WORKERS_COUNT: "{{ $.Values.envs.workers }}"
  SERVER_PORT: "{{ $.Values.ports.server }}"
  STORE_PORT: "{{ $.Values.ports.store }}"
  TM_SERVICE: "{{ .tm_service }}"
  PREFIX: /{{ .name | trimPrefix "telemetry-" }}
  LOCAL_STATSD_PORT: "{{ $.Values.ports.statsd }}"
  LOCAL_STATSD_ENABLED: "{{ $.Values.envs.statsdEnabled }}"
  LOCAL_STATSD_ZABBIX_HOST_FROM_KEY: "{{ $.Values.envs.statsdHostFromKey }}"
  LOCAL_STATSD_PERCENTS: "{{ $.Values.envs.statsdPercents }}"
  WS_ERROR_LOGS_THRESHOLD: "{{ $.Values.envs.logsThreshold }}"
  IGNORE_LOG_TELEMETRY: "{{ $.Values.envs.ignoreLogTelemetry }}"
  DISABLE_PORT_ALLOCATOR: "{{ $.Values.envs.disablePortAllocator }}"
  FACTER_task_id: "{{ .name }}-{{ $.Values.location }}"
  FACTER_cluster_id: "{{ .name }}-{{ $.Values.location }}"
  FACTER_location: "{{ $.Values.location }}"
  ZKHOST: "{{ $.Values.envs.zkHosts }}"
{{- end }}
